### ISSUE TITLE
Pre-compiled shared libraries

### ISSUE THREAD

**Issue by smarlowucf** [aio-libs/multidict#111]
I'm attempting to build a distribution package from the source on PyPi. However, the source contains the compiled shared library _istr.cpython-34m.so.

This causes problems if the arch and Python version don't match up with the library. Manually removing the file from the source solves the problem but it doesn't seem like this should exist in the source package?

I also noticed the source on PyPi does not match up with the source on Github. Github does not contain the _multidict.c file. Is this also a build artifact that was compiled from the pyx file?

The url I'm pulling source from is:
https://files.pythonhosted.org/packages/source/m/multidict/multidict-%{version}.tar.gz

**Comment by webknjaz** [comment]
Hi Sean,

It is intentional that `sdist` contains `*.c` files, so that the user won't
need to have generate them with cython (having it as an extra dependency in
their build process).

I think there should not be any `*.so` files embedded in source
distribution. It may be related to the recent CI/CD improvements. I'm going
to investigate this in a day or two.

On Jul 18, 2017 7:19 PM, "Sean Marlow" <notifications@github.com> wrote:

I'm attempting to build a distribution package from the source on PyPi.
However, the source contains the compiled shared library _
istr.cpython-34m.so.

This causes problems if the arch and Python version don't match up with the
library. Manually removing the file from the source solves the problem but
it doesn't seem like this should exist in the source package?

I also noticed the source on PyPi does not match up with the source on
Github. Github does not contain the _multidict.c file.

The url I'm pulling source from is:
https://files.pythonhosted.org/packages/source/m/
multidict/multidict-%{version}.tar.gz

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aio-libs/multidict/issues/111>, or mute the thread

**Comment by smarlowucf** [comment]
> I think there should not be any `*.so` files embedded in source
> distribution. It may be related to the recent CI/CD improvements. I'm going
> to investigate this in a day or two.

Thanks for the quick response, I noticed between version 2.1.6 and 3.0.0 the `so` file started to appear. PyPi shows a version 2.1.7 but I couldn't fetch any sdist.

**Comment by asvetlov** [comment]
Sorry, I'm traveling now.
Will fix the issue next week if @webknjaz don't do it earlier.

**Comment by dzen** [comment]
Hi there,

I do not see any source package on pypi : https://pypi.python.org/pypi/multidict

**Comment by webknjaz** [comment]
Okay, I see `multidict-3.1.3.tar.gz` for current stable version at https://pypi.python.org/simple/multidict/, but there's no `.tar.gz` for `--pre` release `3.1.4a`. This needs more investigation.

**Comment by webknjaz** [comment]
Wow, it turned out, that Travis user doesn't have access to `dist` dir created indice docker container: https://travis-ci.org/aio-libs/multidict/jobs/254112424#L1258

So permission errors happen when attempting to create `.tar.gz` and remove `.whl`'s

**Comment by webknjaz** [comment]
@asvetlov I think we could commit "empty" `dist` dir to work around this issue.

**Comment by asvetlov** [comment]
Sounds good.
Please make sure that `dist` is not included into tarball and wheels

**Comment by dzen** [comment]
Shouldn't we ignore "dist" in https://github.com/aio-libs/multidict/blob/master/MANIFEST.in ?

**Comment by webknjaz** [comment]
@dzen yeah, looks so. We could also try using `setuptools-git` like aiohttp does.

**Comment by asvetlov** [comment]
Looks like fixed in 3.2

**Comment by smarlowucf** [comment]
Thanks! :+1:
