### ISSUE TITLE
multidict 3.2.0 won't install properly on docker

### ISSUE THREAD

**Issue by mzdeb** [aio-libs/multidict#140]
Steps to reproduce
1. cat Dockerfile
```
FROM ubuntu:14.04

RUN apt-get update && apt-get -y install python3-pip
RUN bash -c "pip3 install multidict==3.2.0"
```
2. docker build -t multidict-test .

Result:
```
Downloading/unpacking multidict==3.2.0
  Downloading multidict-3.2.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/multidict/setup.py) egg_info for package multidict

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'multidict/_multidict.html'
    warning: no previously-included files found matching 'multidict/_multidict.*.so'
    warning: no previously-included files found matching 'multidict/_multidict.pyd'
    warning: no previously-included files found matching 'multidict/_multidict.*.pyd'
    no previously-included directories found matching 'docs/_build'
Installing collected packages: multidict
  Running setup.py install for multidict

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'multidict/_multidict.html'
    warning: no previously-included files found matching 'multidict/_multidict.*.so'
    warning: no previously-included files found matching 'multidict/_multidict.pyd'
    warning: no previously-included files found matching 'multidict/_multidict.*.pyd'
    no previously-included directories found matching 'docs/_build'
    error: can't copy 'multidict/_multidict.c': doesn't exist or not a regular file
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/multidict/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rwpv1_j1-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-3.4

creating build/lib.linux-x86_64-3.4/multidict

copying multidict/__init__.py -> build/lib.linux-x86_64-3.4/multidict

copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.4/multidict

running egg_info

writing multidict.egg-info/PKG-INFO

writing dependency_links to multidict.egg-info/dependency_links.txt

writing top-level names to multidict.egg-info/top_level.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'multidict.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files matching '*.pyc' found anywhere in distribution

warning: no previously-included files found matching 'multidict/_multidict.html'

warning: no previously-included files found matching 'multidict/_multidict.*.so'

warning: no previously-included files found matching 'multidict/_multidict.pyd'

warning: no previously-included files found matching 'multidict/_multidict.*.pyd'

no previously-included directories found matching 'docs/_build'

writing manifest file 'multidict.egg-info/SOURCES.txt'

copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.4/multidict

copying multidict/_istr.c -> build/lib.linux-x86_64-3.4/multidict

error: can't copy 'multidict/_multidict.c': doesn't exist or not a regular file
```

**Comment by mzdeb** [comment]
Sorry, upgrade of pip to newest version resolves problem. Issue can be closed.

**Comment by webknjaz** [comment]
@asvetlov this looks like an issue w/ sdist

**Comment by asvetlov** [comment]
Yes, `.c` file is missing in tarball, need cython to install.

**Comment by deepagargit** [comment]
After installing cython-0.27.2, multidict install gave following error.

multidict-3.3.0$ sudo python setup.py install
Compiling multidict/_multidict.pyx because it changed.
[1/1] Cythonizing multidict/_multidict.pyx
running install
running bdist_egg
running egg_info
writing multidict.egg-info/PKG-INFO
writing top-level names to multidict.egg-info/top_level.txt
writing dependency_links to multidict.egg-info/dependency_links.txt
reading manifest file 'multidict.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '.pyc' found anywhere in distribution
warning: no previously-included files found matching 'multidict/_multidict.html'
warning: no previously-included files found matching 'multidict/_multidict..so'
warning: no previously-included files found matching 'multidict/_multidict.pyd'
warning: no previously-included files found matching 'multidict/_multidict..pyd'
no previously-included directories found matching 'docs/_build'
writing manifest file 'multidict.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying multidict/_multidict.c -> build/lib.linux-x86_64-2.7/multidict
copying multidict/_multidict.pyx -> build/lib.linux-x86_64-2.7/multidict
running build_ext
building 'multidict._multidict' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/multidict
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c multidict/_multidict.c -o build/temp.linux-x86_64-2.7/multidict/_multidict.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/multidict/_multidict.o -o build/lib.linux-x86_64-2.7/multidict/_multidict.so
building 'multidict._istr' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c multidict/_istr.c -o build/temp.linux-x86_64-2.7/multidict/_istr.o
multidict/_istr.c: In function ‘modstate’:
multidict/_istr.c:33:5: warning: implicit declaration of function ‘PyModule_GetState’ [-Wimplicit-function-declaration]
return (ModData)PyModule_GetState(mod);
^
multidict/_istr.c:33:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
return (ModData*)PyModule_GetState(mod);
^
multidict/_istr.c: In function ‘global_state’:
multidict/_istr.c:39:5: warning: implicit declaration of function ‘PyState_FindModule’ [-Wimplicit-function-declaration]
return modstate(PyState_FindModule(&_istrmodule));
^
multidict/_istr.c:39:5: warning: passing argument 1 of ‘modstate’ makes pointer from integer without a cast [enabled by default]
multidict/_istr.c:31:1: note: expected ‘struct PyObject *’ but argument is of type ‘int’
modstate(PyObject mod)
^
multidict/_istr.c: At top level:
multidict/_istr.c:181:15: error: variable ‘_istrmodule’ has initializer but incomplete type
static struct PyModuleDef _istrmodule = {
^
multidict/_istr.c:182:5: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function)
PyModuleDef_HEAD_INIT,
^
multidict/_istr.c:182:5: warning: excess elements in struct initializer [enabled by default]
multidict/_istr.c:182:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:183:5: warning: excess elements in struct initializer [enabled by default]
"multidict._istr",
^
multidict/_istr.c:183:5: warning: (near initialization for ‘istrmodule’) [enabled by default]
multidict/istr.c:184:5: warning: excess elements in struct initializer [enabled by default]
istr__doc,
^
multidict/_istr.c:184:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:185:5: warning: excess elements in struct initializer [enabled by default]
sizeof(ModData),
^
multidict/_istr.c:185:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:186:5: warning: excess elements in struct initializer [enabled by default]
NULL, / m_methods /
^
multidict/_istr.c:186:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:187:5: warning: excess elements in struct initializer [enabled by default]
NULL, / m_reload /
^
multidict/_istr.c:187:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:188:5: warning: excess elements in struct initializer [enabled by default]
NULL, / m_traverse /
^
multidict/_istr.c:188:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:189:5: warning: excess elements in struct initializer [enabled by default]
mod_clear, / m_clear */
^
multidict/_istr.c:189:5: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c:191:1: warning: excess elements in struct initializer [enabled by default]
};
^
multidict/_istr.c:191:1: warning: (near initialization for ‘_istrmodule’) [enabled by default]
multidict/_istr.c: In function ‘PyInit__istr’:
multidict/_istr.c:199:9: warning: assignment makes pointer from integer without a cast [enabled by default]
mod = PyState_FindModule(&_istrmodule);
^
multidict/_istr.c:210:5: warning: implicit declaration of function ‘PyModule_Create’ [-Wimplicit-function-declaration]
mod = PyModule_Create(&_istrmodule);
^
multidict/_istr.c:210:9: warning: assignment makes pointer from integer without a cast [enabled by default]
mod = PyModule_Create(&_istrmodule);
^
multidict/_istr.c:219:5: warning: implicit declaration of function ‘PyUnicode_New’ [-Wimplicit-function-declaration]
tmp = PyUnicode_New(0, 0);
^
multidict/_istr.c:219:9: warning: assignment makes pointer from integer without a cast [enabled by default]
tmp = PyUnicode_New(0, 0);
^
Traceback (most recent call last):
File "setup.py", line 100, in 
setup(**args)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
self.do_egg_install()
File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 88, in do_egg_install
self.run_command('bdist_egg')
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 185, in run
cmd = self.call_command('install_lib', warn_dir=0)
File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 171, in call_command
self.run_command(cmdname)
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 21, in run
self.build()
File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
self.run_command('build_ext')
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 43, in run
except (DistutilsPlatformError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined

**Comment by asvetlov** [comment]
Run install against python 3
